University_Manager/Models/AssignCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using University_Manager.Models;

namespace University_Manager.Models
{
    public class AssignCourse
    {
        public int AssignCourseId { set; get; }
        [Required(ErrorMessage = "Department can't be empty")]
        public int DepartmentId { set; get; }
        public virtual Department Department { set; get; }
        [Required(ErrorMessage = "Teacher can't empty")]
        public int TeacherId { set; get; }
        public virtual Teacher Teacher { set; get; }
        public virtual double CreditTaken { set; get; }
        public virtual double RemaingCredit { set; get; }
        [Required(ErrorMessage = "Course can't empty")]
        public int CourseId { set; get; }
        public virtual Course Course { set; get; }

        

    }
}

University_Manager/Controllers/AssignCourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using University_Manager.Models;

namespace University_Manager.Controllers
{
    [Authorize]
    public class AssignCourseController : Controller
    {
        private UniversityDbContex db = new UniversityDbContex();

        //
        // GET: /AssignCourse/

        public ActionResult Index()
        {
            var assigncourses = db.AssignCourses.Include(a => a.Department).Include(a => a.Teacher).Include(a => a.Course);
            return View(assigncourses.ToList());
        }

        //
        // GET: /AssignCourse/Details/5

        public ActionResult Details(int id = 0)
        {
            AssignCourse assigncourse = db.AssignCourses.Find(id);
            if (assigncourse == null)
            {
                return HttpNotFound();
            }
            return View(assigncourse);
        }

        //
        // GET: /AssignCourse/Create

        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            ViewBag.TeacherId = new SelectList("", "TeacherId", "Name");
            ViewBag.CourseId = new SelectList("", "CourseId", "Code");
            return View();
        }

        //
        // POST: /AssignCourse/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AssignCourse assigncourse)
        {
            if (ModelState.IsValid)
            {
                var result =
                    db.AssignCourses.Count(
                        r => r.CourseId == assigncourse.CourseId ) == 0;

                if (result)
                {
                    Teacher aTeacher = db.Teachers.FirstOrDefault(t => t.TeacherId == assigncourse.TeacherId);
                    Course aCourse = db.Courses.FirstOrDefault(c => c.CourseId == assigncourse.CourseId);
                    List<AssignCourse> assignTeachers =
                        db.AssignCourses.Where(t => t.TeacherId == assigncourse.TeacherId).ToList();
                    AssignCourse assign = null;
                    if (assignTeachers.Count != 0)
                    {
                        
                        assign = assignTeachers.Last();
                        assigncourse.RemaingCredit = assign.RemaingCredit;
                    }
                    else
                    {
                        assigncourse.RemaingCredit = aTeacher.CreditTaken;
                    }
                    
                    //if (assign == null)
                    //    assigncourse.RemaingCredit = aTeacher.CreditTaken;
                    
                    if (assigncourse.RemaingCredit < aCourse.Credit)
                    {
                        Session["Teacher"] = aTeacher;
                        Session["Course"] = aCourse;
                        Session["AssignedCourse"] = assigncourse;
                        Session["AssigneddCourseCheck"] = assign;
                        return RedirectToAction("AskToAssign");
                    }

                    assigncourse.CreditTaken = aTeacher.CreditTaken;

                    if (assign == null)
                    {
                        assigncourse.RemaingCredit = aTeacher.CreditTaken - aCourse.Credit;
                    }
                    else
                    {
                        assigncourse.RemaingCredit = assign.RemaingCredit - aCourse.Credit;
                    }

                    aCourse.AssignTo = aTeacher.Name;

                    db.AssignCourses.Add(assigncourse);
                    db.SaveChanges();
                    TempData["success"] = "Course Assigned";
                    return RedirectToAction("Create");
                }
                else
                {
                    TempData["Already"] = "Course Has Already Been Assigned";
                    return RedirectToAction("Create");
                }
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", assigncourse.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "Name", assigncourse.TeacherId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", assigncourse.CourseId);
            return View(assigncourse);
        }

        public ActionResult AskToAssign()
        {
            Teacher aTeacher = (Teacher)Session["Teacher"];
            Course aCourse = (Course)Session["Course"];
            AssignCourse assign = (AssignCourse) Session["AssigneddCourseCheck"];
            double remainingCredite =0.0;
            if (assign == null)
                remainingCredite = aTeacher.CreditTaken;
            else
            {
                remainingCredite = assign.RemaingCredit;
            }
            if (remainingCredite < 0)
            {
                ViewBag.Message = aTeacher.Name
                + " Credit Limit Is Over. And The Course Credit  : " + aCourse.Code
                + " Is " + aCourse.Credit
                + "  ! Still You Want To Assign This Course To This Teacher ?";
            }
            else
            {
                ViewBag.Message = aTeacher.Name
                + " has only " + remainingCredite
                + " Credits Remaining . But, The Credit  : " + aCourse.Code
                + " Is " + aCourse.Credit
                + "  ! Still You Want To Assign This Course To This Teacher ?";
            }
            
            return View();
        }

        public ActionResult AssignConfirmed()
        {
            Teacher aTeacher = (Teacher)Session["Teacher"];
            
            AssignCourse assigncourse = (AssignCourse)Session["AssignedCourse"];
            AssignCourse assign = (AssignCourse)Session["AssigneddCourseCheck"];
            Course aCourse = db.Courses.FirstOrDefault(c => c.CourseId == assigncourse.CourseId);
           

            assigncourse.CreditTaken = aTeacher.CreditTaken;
            if (assign == null)
            {
                assigncourse.RemaingCredit = aTeacher.CreditTaken - aCourse.Credit;
            }
            else
            {
                assigncourse.RemaingCredit = assign.RemaingCredit - aCourse.Credit;
            }

            aCourse.AssignTo = aTeacher.Name;

            db.AssignCourses.Add(assigncourse);
            db.SaveChanges();
            TempData["success"] = "Course Is Assigned";
            return View();
        }

        //
        // GET: /AssignCourse/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AssignCourse assigncourse = db.AssignCourses.Find(id);
            if (assigncourse == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", assigncourse.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "Name", assigncourse.TeacherId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", assigncourse.CourseId);
            return View(assigncourse);
        }

        //
        // POST: /AssignCourse/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AssignCourse assigncourse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assigncourse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", assigncourse.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "Name", assigncourse.TeacherId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Code", assigncourse.CourseId);
            return View(assigncourse);
        }

        //
        // GET: /AssignCourse/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AssignCourse assigncourse = db.AssignCourses.Find(id);
            if (assigncourse == null)
            {
                return HttpNotFound();
            }
            return View(assigncourse);
        }

        //
        // POST: /AssignCourse/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AssignCourse assigncourse = db.AssignCourses.Find(id);
            db.AssignCourses.Remove(assigncourse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public ActionResult LoadTeacher(int? departmentId)
        {
            var teacherList = db.Teachers.Where(u => u.DepartmentId == departmentId).ToList();
            ViewBag.TeacherId = new SelectList(teacherList, "TeacherId", "Name");
            return PartialView("~/Views/Shared/_FillteredTeacher.cshtml");
        }

        public ActionResult LoadCourse(int? departmentId)
        {
            var courseList = db.Courses.Where(u => u.DepartmentId == departmentId).ToList();
            ViewBag.CourseId = new SelectList(courseList, "CourseId", "Name");
            return PartialView("~/Views/shared/_FilteredCourse.cshtml");

        }

        public PartialViewResult TeacherInfoLoad(int? teacherId)
        {
            if (teacherId != null)
            {

University_Manager/Views/AssignCourse/AskToAssign.cshtml
@{
    ViewBag.Title = "Ask To Assign";
}

<h2>Assign confirmation </h2>

<div><h3 style="color: chocolate">@ViewBag.Message</h3></div>

<form action="AssignConfirmed">
    <input type="submit" value="Assign" class="btn btn-success"/>
</form>
<p><br/></p>
<form action="Create">
    <input type="submit" value="Cancel" class="btn btn-warning"/>
</form>

University_Manager/Views/AssignCourse/AssignConfirmed.cshtml
@{
    ViewBag.Title = "AssignConfirmed";
}

<h2>Assign Confirmed</h2>


<div><h3 style="color: chocolate">@TempData["Already"]</h3></div>

<p class="btn btn-success">
    @Html.ActionLink("Assaign Course", "Create")
</p>

University_Manager/Views/AssignCourse/Create.cshtml
@using University_Manager.Controllers
@model University_Manager.Models.AssignCourse

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js" type="text/javascript"></script>

<h2>Course Assign to Teacher</h2>
<h3 style="color:forestgreen">@TempData["success"]</h3>
<h3 style="color: red">@TempData["Already"]</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
   

    <fieldset>

        <div class="editor-label">
            @Html.LabelFor(model => model.DepartmentId, "Department")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DepartmentId", String.Empty)
            @Html.ValidationMessageFor(model => model.DepartmentId)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.TeacherId, "Teacher")
        </div>
        <div class="editor-field">
            @Html.Partial("_FillteredTeacher")
            @Html.ValidationMessageFor(model => model.TeacherId)
        </div>
        <div id="teacherInfo">
            @Html.Partial("~/Views/Shared/_TeachersCreditInfo.cshtml")
        </div>


     

        <div class="editor-label">
            @Html.LabelFor(model => model.CourseId, "Course")
        </div>
        <div class="editor-field">
            @Html.Partial("_FilteredCourse")
            @Html.ValidationMessageFor(model => model.CourseId)
        </div>
        <div id="courseInfo">
            @Html.Partial("~/Views/Shared/_CourseInfo.cshtml")
        </div>

        <p>
            <input type="submit" value="Assign" class="btn btn-primary" />
            
        </p>
    </fieldset>
}

<script type="text/javascript">
    function FillData(id) {

        $('#TeacherId').load('@Url.Action("LoadTeacher")', { departmentId: id });
        $('#CourseId').load('@Url.Action("LoadCourse")', { departmentId: id });

    }
    function FillTeacherInfo(id) {

        $('#teacherInfo').load('@Url.Action("TeacherInfoLoad")', { teacherId: id });

    }
    function FillCourseInfo(id) {

        $('#courseInfo').load('@Url.Action("CourseInfoLoad")', { courseId: id });

    }

    $(function () {
        $('#DepartmentId').change(function () {
            var id = $('#DepartmentId').val();
            FillData(id);
        });
        $('#TeacherId').change(function () {
            var id = $('#TeacherId').val();
            FillTeacherInfo(id);
        });
        $('#CourseId').change(function () {
            var id = $('#CourseId').val();
            FillCourseInfo(id);
        });
    });
</script>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

University_Manager/Views/AssignCourse/Delete.cshtml
@model University_Manager.Models.AssignCourse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>AssignCourse</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Department.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Department.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Teacher.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Teacher.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreditTaken)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreditTaken)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RemaingCredit)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RemaingCredit)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Course.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Course.Code)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

University_Manager/Views/AssignCourse/Details.cshtml
@model University_Manager.Models.AssignCourse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>AssignCourse</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Department.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Department.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Teacher.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Teacher.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreditTaken)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreditTaken)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RemaingCredit)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RemaingCredit)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Course.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Course.Code)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.AssignCourseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

University_Manager/Views/AssignCourse/Edit.cshtml
@model University_Manager.Models.AssignCourse

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AssignCourse</legend>

        @Html.HiddenFor(model => model.AssignCourseId)

        <div class="editor-label">
            @Html.LabelFor(model => model.DepartmentId, "Department")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DepartmentId", String.Empty)
            @Html.ValidationMessageFor(model => model.DepartmentId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TeacherId, "Teacher")
        </div>
        <div class="editor-field">
            @Html.DropDownList("TeacherId", String.Empty)
            @Html.ValidationMessageFor(model => model.TeacherId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreditTaken)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreditTaken)
            @Html.ValidationMessageFor(model => model.CreditTaken)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RemaingCredit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RemaingCredit)
            @Html.ValidationMessageFor(model => model.RemaingCredit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CourseId, "Course")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CourseId", String.Empty)
            @Html.ValidationMessageFor(model => model.CourseId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

University_Manager/Views/AssignCourse/Index.cshtml
@model List<University_Manager.Models.AssignCourse>
@{
    ViewBag.Title = "Assign Course";
}
<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <span class="glyphicon glyphicon-th"></span><h4 class="title">ASSIGN COURSE</h4>
        <input type="button" class="btn btn-default pull-right btp" value="Assign Course" onclick="location.href='@Url.Action("Create", "AssignCourse")'" />
    </div>
    <div class="container-outer" style="padding:10px">
        <table id="myTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Department")
                    </th>
                    <th>
                        @Html.DisplayName("Teacher")
                    </th>
                    <th>
                        @Html.DisplayName("Credit Taken")
                    </th>
                    <th>
                        @Html.DisplayName("Remaing Credit")
                    </th>
                    <th>
                        @Html.DisplayName("Course")
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Teacher.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreditTaken)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemaingCredit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Code)
                    </td>
                    @*<td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.AssignCourseId }) |
                            @Html.ActionLink("Details", "Details", new { id=item.AssignCourseId }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.AssignCourseId })
                        </td>*@
                </tr>
            }
        </table>
    </div>
</div>

University_Manager/Views/AssignCourse/ViewCourseStatus.cshtml
@model IEnumerable<University_Manager.Models.Course>
@{
    ViewBag.Title = "ViewCourseStatus";
}

<h2>View Course Status</h2>

<script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js" type="text/javascript"></script>


@using (Html.BeginForm())
{
    <div>
        <b>Select Department  </b>
        @Html.DropDownList("DepartmentId", "Select Department")
    </div>
}
<p><br/></p>
<div id="resultData">
    @Html.Partial("~/Views/Shared/_coursestatus.cshtml")
</div>

<script type="text/javascript">
    function FillData(id) {
        $('#resultData').load('@Url.Action("CourseStatusLoad")', { departmentId: id });
    }

    $(function () {
        $('#DepartmentId').change(function () {
            var id = $('#DepartmentId').val();
            FillData(id);
        });
    });

</script>